apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../_commons/services/defid-masternode

patches:
  - path: statefulset.patch.yaml
    target:
      kind: StatefulSet
      name: defid-masternode
