# TODO: 
# - Switch to owner to groups
# - Make project, org and billing vars input propogate from higher components.

- name: Setup GCP Project
  hosts: localhost
  vars:
    project_id: dfi-labs-dev-tf3
    organization_id: 564950325795
    owner: prasanna@cakedefi.com
    billing_account_id: 01F606-D04835-3532AB # Legacy
    # billing_account_id: 01BA6B-33D914-55E186 # 2024-1
    # -- Derived
    project_name: "{{ project_id }}"
    tf_service_account_name: tf-service-account
    tf_service_account_id: "{{ tf_service_account_name }}@{{ project_id }}.iam.gserviceaccount.com"
    tf_service_account_desc: Terraform Service Account
    gcs_bucket_name: "{{ project_id }}-state"
    gcs_lifecycle_json_file: "{{ playbook_dir }}/gcp-setup-project-gcs-lifecycle-tfstate.json"
  tasks:
    - name: "Create project: {{ project_id }}"
      command: gcloud projects create "{{ project_id }}" --name="{{ project_name }}" --organization="{{ organization_id }}"
      ignore_errors: true
    - name: "Link billing account: {{ billing_account_id }}"
      command: gcloud billing projects link "{{ project_id }}" --billing-account="{{ billing_account_id }}"
    - name: "Create service account: {{ tf_service_account_name }}"
      command: gcloud iam service-accounts create "{{ tf_service_account_name }}" --description="{{ tf_service_account_desc }}" --display-name="{{ tf_service_account_desc }}" --project="{{ project_id }}"
      ignore_errors: true
    - name: "Add project iam: role: editor"
      command: gcloud projects add-iam-policy-binding "{{ project_id }}" --member="serviceAccount:{{ tf_service_account_id }}" --role="roles/editor" --project="{{ project_id }}"
    - name: "Add service account iam: role: serviceAccountTokenCreator"
      command: gcloud iam service-accounts add-iam-policy-binding "{{ tf_service_account_id }}" --member="user:{{ owner }}" --role="roles/iam.serviceAccountTokenCreator" --project="{{ project_id }}"
    - name: "Create bucket: {{ gcs_bucket_name }}"
      command: gsutil mb -p "{{ project_id }}" "gs://{{ gcs_bucket_name }}"
      ignore_errors: true
    - name: "Set versioning on bucket: {{ gcs_bucket_name }}"
      command: gsutil versioning set on "gs://{{ gcs_bucket_name }}"
    - name: "Set versioning lifecycle policy on bucket: {{ gcs_bucket_name }}"
      command: gsutil lifecycle set "{{ gcs_lifecycle_json_file }}" "gs://{{ gcs_bucket_name }}"
