---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blockscout

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: stats

configMapGenerator:
  - name: proxy
    files:
      - nginx.conf
