---
apiVersion: v1
kind: Service
metadata:
  name: stats
spec:
  type: ClusterIP
  ports:
    - name: stats
      port: 8050
      protocol: TCP
      targetPort: 8050
    - name: proxy
      port: 80
      protocol: TCP
      targetPort: 80
