"cloud/cloudflare":
  - changed-files:
      - any-glob-to-any-file: tf/cloudflare/**

"cloud/linode":
  - changed-files:
      - any-glob-to-any-file: tf/linode/**

"cloud/aws":
  - changed-files:
      - any-glob-to-any-file: tf/aws/**

"cloud/gcp":
  - changed-files:
      - any-glob-to-any-file: tf/gcp/**

"tool/terraform":
  - changed-files:
      - any-glob-to-any-file:
          - tf/**

"tool/ansible":
  - changed-files:
      - any-glob-to-any-file:
          - ansible/**

"tool/k8s":
  - changed-files:
      - any-glob-to-any-file:
          - k8s/**
