apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacy-stats
  template:
    metadata:
      labels:
        app: legacy-stats
    spec:
      containers:
        - name: legacy-stats
          image: ghcr.io/birthdayresearch/legacy-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2000Mi
            requests:
              cpu: 500m
              memory: 1000Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /_actuator/probes/readiness
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
