---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    spec:
      restartPolicy: Always
      containers:
        - name: frontend
          image: 637423481667.dkr.ecr.ap-southeast-1.amazonaws.com/github/blockscout/frontend:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: frontend
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
            requests:
              cpu: 500m
              memory: 500Mi
