---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - statefulset.yaml

configMapGenerator:
  - name: defi-init
    files:
      - init.sh

commonLabels:
  app: defid-masternode
