---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../_commons/controllers/aws-load-balancer-controller

patches:
  - path: values.yaml
    target:
      kind: Application
      name: aws-load-balancer-controller
