---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-driver
spec:
  source:
    helm:
      valuesObject:
        fullnameOverride: "ebs-csi-driver"
        controller:
          serviceAccount:
            annotations:
              "eks.amazonaws.com/role-arn": "arn:aws:iam::637423481667:role/dfi-ocean-mainnet-aps1-ebs-csi-driver"
        sidecars:
          snapshotter:
            # Enables the snapshotter sidecar even if the snapshot CRDs are not installed
            forceEnable: true
