apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
secretFrom:
  - metadata:
      name: defi-secrets
      annotations:
        kustomize.config.k8s.io/needs-hash: "true"
    files:
      - defi.conf=defi.enc.conf
