---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualizer
spec:
  selector:
    matchLabels:
      app: visualizer
  template:
    spec:
      restartPolicy: Always
      containers:
        - name: visualizer
          image: ghcr.io/blockscout/visualizer:latest
          imagePullPolicy: Always
          env:
            - name: VISUALIZER__SERVER__GRPC__ENABLED
              value: "false"
          ports:
            - containerPort: 8050
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 4000Mi
            requests:
              cpu: "1"
              memory: 2000Mi
