apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: masternodes

nameSuffix: -cdt

images:
  - name: defi/defichain
    newTag: 4.1.1

resources:
  - defid-masternode

configMapGenerator:
  - name: defid
    envs:
      - configs/defid.env

patches:
  - patch: |
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::637423481667:role/dfi-ocean-mainnet-aps1-snapshotter
    target:
      kind: ServiceAccount
      name: defid-masternode
