apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blockscout

images:
  - name: 637423481667.dkr.ecr.ap-southeast-1.amazonaws.com/github/blockscout/sig-provider
    newTag: v1.0.0
  - name: 637423481667.dkr.ecr.ap-southeast-1.amazonaws.com/github/blockscout/smart-contract-verifier
    newTag: v1.8.0
  - name: 637423481667.dkr.ecr.ap-southeast-1.amazonaws.com/github/blockscout/visualizer
    newTag: v0.2.0
  - name: 637423481667.dkr.ecr.ap-southeast-1.amazonaws.com/github/blockscout/stats
    newTag: v1.6.0
  - name: 637423481667.dkr.ecr.ap-southeast-1.amazonaws.com/dockerhub/blockscout/blockscout
    newTag: 6.7.0
  - name: 637423481667.dkr.ecr.ap-southeast-1.amazonaws.com/github/blockscout/frontend
    newTag: v1.31.1

resources:
  - ../../../_commons/services/blockscout

configMapGenerator:
  - name: blockscout
    envs:
      - configs/blockscout.env
  - name: frontend
    envs:
      - configs/frontend.env
  - name: stats
    envs:
      - configs/stats.env

generators:
  - secrets/secret-generator.yaml
