---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../_commons/controllers/rancher

patches:
  - path: values.yaml
    target:
      kind: Application
      name: rancher
