---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-driver
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: aws-ebs-csi-driver
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    targetRevision: "2.22.0"
    helm:
      releaseName: aws-ebs-csi-driver
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
