---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - SGInstanceProfile.yaml
  - SGPoolingConfig.yaml
  - SGPostgresConfig.yaml
  - SGScript.yaml
  - SGCluster.yaml

commonLabels:
  app: database
