apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: masternodes

nameSuffix: -bake

images:
  - name: 637423481667.dkr.ecr.ap-southeast-1.amazonaws.com/dockerhub/defi/defichain
    newTag: 4.2.4

resources:
  - defid-masternode

configMapGenerator:
  - name: defid
    envs:
      - configs/defid.env

# Just a placeholder. Use S3 bucket instead to pull due to K8s 1mb secret limitation
secretGenerator:
  - name: defi-secrets
    literals:
      - defi.conf=placeholder
      - keys.private=placeholder

patches:
  - patch: |
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::637423481667:role/dfi-ocean-mainnet-aps1-snapshotter
    target:
      kind: ServiceAccount
      name: defid-masternode
