apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "001"
  - "002"
  - "003"
  - "004"
  - "005"
  - "006"
  - "007"
  - "008"
  - "009"
  - "010"

patches:
  - path: statefulset.patch.yaml
    target:
      kind: StatefulSet
      name: defid-masternode
