apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocean

images:
  - name: 637423481667.dkr.ecr.ap-southeast-1.amazonaws.com/github/birthdayresearch/whale-api
    newTag: 4.0.7
  - name: 637423481667.dkr.ecr.ap-southeast-1.amazonaws.com/dockerhub/defi/defichain
    newTag: 4.2.1

resources:
  - defid
  - defid-snapshotter
  - whale
  - legacy-stats
  - snapshots

configMapGenerator:
  - name: defi-conf
    files:
      - configs/defi.conf
  - name: whale
    envs:
      - configs/whale.env
  - name: defid-snapshotter
    envs:
      - configs/snapshotter.env
  - name: defid
    envs:
      - configs/defid.env

patches:
  - patch: |
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::637423481667:role/dfi-ocean-mainnet-aps1-snapshotter
    target:
      kind: ServiceAccount
      name: defid-snapshotter
  - patch: |
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::637423481667:role/dfi-ocean-mainnet-aps1-snapshotter
    target:
      kind: ServiceAccount
      name: whale
  - patch: |
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::637423481667:role/dfi-ocean-mainnet-aps1-snapshotter
    target:
      kind: ServiceAccount
      name: defid

commonLabels:
  type: stable
