# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    kms: arn:aws:kms:ap-southeast-1:637423481667:key/df82460c-2d1f-4d3b-861a-e268b8ecfcd1
