---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend
  - frontend
  - indexer
  - stats
  - visualizer
  - smart-contract-verifier

commonLabels:
  service: blockscout
