- name: Setup node
  hosts: all
  remote_user: x
  vars:
    dfi_version: 4.0.9
    dfi_node_filename: "defichain-{{ dfi_version }}-x86_64-pc-linux-gnu"
    dfi_node_filename_tar: "{{ dfi_node_filename }}.tar.gz"
    dfi_node_url: "https://github.com/DeFiCh/ain/releases/download/v{{ dfi_version }}/{{ dfi_node_filename_tar }}"
  tasks:
    # Start with graceful exits
    - name: systemctl stop defid
      command: systemctl stop defid
      ignore_errors: yes
    - name: Stop existing node
      command: defi-cli stop
      ignore_errors: yes
    - name: kill defid
      command: kill defid
      ignore_errors: yes
    - name: sleep 30s
      pause:
        seconds: 30
