---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
spec:
  source:
    helm:
      valuesObject:
        hostname: rancher.changi.ocean.jellyfishsdk.com
        tls: external
        ingress:
          enabled: false
