---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../_commons/controllers/aws-ebs-csi-driver
  - gp3.storage-class.yaml

patches:
  - path: values.yaml
    target:
      kind: Application
      name: aws-ebs-csi-driver
