---
apiVersion: v1
kind: Service
metadata:
  name: smart-contract-verifier
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8050
      protocol: TCP
      targetPort: 8050
    - name: grpc
      port: 8051
      protocol: TCP
      targetPort: 8051
