---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-stats
spec:
  replicas: 3
  selector:
    matchLabels:
      app: legacy-stats
  template:
    metadata:
      labels:
        app: legacy-stats
    spec:
      containers:
        - name: legacy-stats
          resources:
            limits:
              cpu: "1"
              memory: 2000Mi
            requests:
              cpu: 500m
              memory: 1000Mi
