name: PR Labeler

on: [pull_request]

permissions:
  contents: read

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@8b99f404a073744885d8021d1de4e40c6eaf38e2 # @v4.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
