name: "Semantic Title Check"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions: read-all

jobs:
  main:
    name: Validate PR title
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # https://github.com/commitizen/conventional-commit-types/blob/master/index.json
      - uses: amannn/action-semantic-pull-request@e9fabac35e210fea40ca5b14c0da95a099eff26f # v5.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
