---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: whale
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: whale
          resources:
            limits:
              cpu: "2"
              memory: 4000Mi
            requests:
              cpu: "1"
              memory: 2000Mi
  volumeClaimTemplates:
    - metadata:
        name: snapshot
      spec:
        storageClassName: "gp3"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 320Gi
    - metadata:
        name: whale
      spec:
        storageClassName: "gp3"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 320Gi
